version: 2.1
orbs:
  slack: circleci/slack@4.12.1
jobs:
  build-code:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    docker:
    # Use the same Docker base as the project
      - image: maven:3.9-amazoncorretto-17    
    steps:      
      - checkout:
          path: ~/udacitycicd
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-target-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-target-
      - run:
          name: install dependencies
          command: |
            mvn -DskipTests install      
      - save_cache:
          paths:
            - ./target
          key: v1-target-{{ checksum "pom.xml" }} 
  lint-code:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    docker:    
      - image: maven:3.9-amazoncorretto-17    
    steps:     
      - checkout:
          path: ~/udacitycicd      
      - run:
          name: Check Bugs
          command: |
            mvn spotbugs:check            
  lint-docker:
    working_directory: ~/udacitycicd
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3    
    steps:
      - checkout:
          path: ~/udacitycicd
      - run:
          name: Get HadoLint
          command: |
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64                 
      - run:
          name: Install HadoLint
          command: |
            # Install hadolint            
            chmod +x /bin/hadolint
            export PATH=$PATH:/bin/hadolint
      - run:
          name: Lint Docker file
          command: |
            hadolint --ignore DL3013 Dockerfile

workflows:
  default:
    jobs:
      - build-code
      - lint-code
      - lint-docker

