version: 2.1
orbs:
  slack: circleci/slack@4.12.1
executors:
  docker-publisher:
    environment:
      IMAGE_TAG: avneeshver/udacitycapstoneproj:1.0
    docker:
      - image: docker:stable
jobs:
  build-code:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    docker:
    # Use the same Docker base as the project
      - image: maven:3.9-amazoncorretto-17    
    steps:      
      - checkout:
          path: ~/udacitycicd      
      - restore_cache:
          keys:
            - v1-target-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-target-
      - run:
          name: install dependencies
          command: |
            mvn -DskipTests install
            mvn -DskipTests package      
      - save_cache:
          paths:
            - ./target
          key: v1-target-{{ checksum "pom.xml" }} 
  lint-code:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    docker:    
      - image: maven:3.9-amazoncorretto-17    
    steps:     
      - checkout:
          path: ~/udacitycicd  
      - restore_cache:
          keys:
            - v1-target-{{ checksum "pom.xml" }}            
      - run:
          name: Check Bugs
          command: |
            mvn spotbugs:check            
  lint-docker:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3    
    steps:
      - checkout:
          path: ~/udacitycicd
      - run:
          name: Get HadoLint
          command: |
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64                 
      - run:
          name: Install HadoLint
          command: |
            # Install hadolint            
            chmod +x /bin/hadolint
            export PATH=$PATH:/bin/hadolint
      - run:
          name: Lint Docker file
          command: |
            hadolint --ignore DL3013 Dockerfile
  build-publish-image:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    executor: docker-publisher
    steps:
      - checkout:
          path: ~/udacitycicd 
      - restore_cache:
          keys:
            - v1-target-{{ checksum "pom.xml" }}
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |            
            docker build --tag "${IMAGE_TAG}" .
      - run:
          name: Publish Docker image
          command: |
            echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            docker push "${IMAGE_TAG}"     
workflows:
  default:
    jobs:
      - build-code
      - lint-code:
          requires:
            - build-code
      - lint-docker:
          requires:
            - build-code
      - build-publish-image:
          requires:
            - lint-code
            - lint-docker

