# Python CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    docker:
    # Use the same Docker base as the project
      - image: maven:3.8.3-openjdk-17    
    steps:
      - install wget:
          apt-get install wget
      - checkout:
          path: ~/udacitycicd
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-target-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-target-
      - run:
          name: install dependencies
          command: |
            mvn -DskipTests install
      - run:
          name: Get HadoLint
          command: |
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64                 
      - run:
          name: Install HadoLint
          command: |
            # Install hadolint            
            chmod +x /bin/hadolint
            export PATH=$PATH:/bin/hadolint
      - save_cache:
          paths:
            - ./target
          key: v1-target-{{ checksum "pom.xml" }}     
