version: 2.1
orbs:
  slack: circleci/slack@4.12.1
executors:
  docker-publisher:
    environment:
      IMAGE_TAG: avneeshver/udacitycapstoneproj:2.0
    docker:
      - image: docker:stable
jobs:
  build-code:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    docker:
    # Use the same Docker base as the project
      - image: maven:3.9-amazoncorretto-17    
    steps:      
      - checkout:
          path: ~/udacitycicd      
      - restore_cache:
          keys:
            - v1-target-{{ checksum "pom.xml" }}
      - run:
          name: install dependencies
          command: |
            mvn -DskipTests install
            mvn -DskipTests package      
      - save_cache:
          paths:
            - ./target
          key: v1-target-{{ checksum "pom.xml" }} 
  lint-code:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    docker:    
      - image: maven:3.9-amazoncorretto-17    
    steps:     
      - checkout:
          path: ~/udacitycicd  
      - restore_cache:
          keys:
            - v1-target-{{ checksum "pom.xml" }}            
      - run:
          name: Check Bugs
          command: |
            mvn spotbugs:check            
  lint-docker:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3    
    steps:
      - checkout:
          path: ~/udacitycicd
      - run:
          name: Get HadoLint
          command: |
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64                 
      - run:
          name: Install HadoLint
          command: |
            # Install hadolint            
            chmod +x /bin/hadolint
            export PATH=$PATH:/bin/hadolint
      - run:
          name: Lint Docker file
          command: |
            hadolint --ignore DL3013 Dockerfile
  build-publish-image:
    working_directory: ~/udacitycicd/src/udacitycapstoneproj
    executor: docker-publisher
    steps:
      - checkout:
          path: ~/udacitycicd 
      - restore_cache:
          keys:
            - v1-target-{{ checksum "pom.xml" }}
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |            
            docker build --tag "${IMAGE_TAG}" .
      - run:
          name: Publish Docker image
          command: |            
            echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            docker push "${IMAGE_TAG}"     
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: 
          name: Install Git
          command: |
            yum update -y && yum install git -y
      - run:
          name: check git version
          command: |
            git --version          
      - checkout
      - run:
          name: Deploy infrastructure   
          no_output_timeout: 30m       
          command: |            
            cd infrastructure
            aws cloudformation deploy \
            --stack-name udacitycapstone-${CIRCLE_WORKFLOW_ID:0:5} \
            --tags project=udacitycapstone \
            --template-file eksvpcsubnets.yaml \
            --parameter-overrides file://eksparameters.json \
            --region "us-east-1" \
            --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

  deploy-application:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: 
          name: Install Git
          command: |
            yum update -y && yum install git -y
      - run:
          name: check git version
          command: |
            git --version          
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -O  https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.2/2023-03-17/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin 
            cp ./kubectl $HOME/bin/kubectl
            export PATH=$HOME/bin:$PATH            
            echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc            
      - run:
          name: Display kubectl version
          command: |
            ./kubectl version --short --client
      - run:
          name: Create kubeconfig
          command: |
            aws eks --region us-east-1 update-kubeconfig --name avudacapstone-eks-cluster
      - run:
          name: Deploy application             
          command: |                        
            ./kubectl apply -f ./deployment/k8-applicationdeployment.yml            
      - run:
          name: Deploy application  Service
          command: |                                    
            ./kubectl apply -f ./deployment/k8-capstoneservice.yml                        
      - run:
          name: Deploy application  Scaler
          command: |                                                
            ./kubectl apply -f ./deployment/k8-scaler.yml
      - run:
          name: Describe application Service
          command: |                                    
             ./kubectl describe service av-capstone-application                        
      - run:
          name: Describe application deployment
          command: |                                    
             ./kubectl describe deployment av-capstone-application      
      - run:
          name: Describe application Pods
          command: |                                    
             ./kubectl get pods -o wide                          
  smoketest-application:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: 
          name: Install Git
          command: |
            yum update -y && yum install git -y
      - run:
          name: check git version
          command: |
            git --version          
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -O  https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.2/2023-03-17/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin 
            cp ./kubectl $HOME/bin/kubectl
            export PATH=$HOME/bin:$PATH            
            echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc            
      - run:
          name: Display kubectl version
          command: |
            ./kubectl version --short --client
      - run:
          name: Create kubeconfig
          command: |
            aws eks --region us-east-1 update-kubeconfig --name avudacapstone-eks-cluster
      - run:
          name: Test application
          command: |
            chmod +x ./test/smoketest.sh           
            ./test/smoketest.sh

workflows:
  default:
    jobs:      
      - build-code
      - lint-code:
          requires:
            - build-code
      - lint-docker:
          requires:
            - build-code
      - build-publish-image:
          requires:
            - lint-code
            - lint-docker
      - deploy-infrastructure:
          requires:
            - build-publish-image
          filters:
            branches:
              only:
                - infrastructure      
      - deploy-application:
          requires:
            - build-publish-image
      - smoketest-application:
          requires:
            - deploy-application