apiVersion: v1
kind: Service
metadata:
  name: av-capstone-application
spec:
  type: LoadBalancer
  selector:
    app: av-capstone-application
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080